=== pZeroWind/Project_Fantasy/Assets/Resources/StateMachine/stateMachineSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:tns="http://example.com/stateMachine" elementFormDefault="qualified" targetNamespace="http://example.com/stateMachine" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="State">
    <xs:complexType>
      <xs:sequence>
        <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ActionEvents">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="AnimationPlayAction">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="Name" />
              <xs:element minOccurs="0" name="Time" />
              <xs:element minOccurs="0" name="Duration" />
              <xs:element minOccurs="0" name="Condition">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="DirectionCondition">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="Direction" />
                          <xs:element minOccurs="0" name="Invert" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="InputMoveCondition">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="Invert" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="EffectPlayAction">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="Name" />
              <xs:element minOccurs="0" name="Time" />
              <xs:element minOccurs="0" name="Duration" />
              <xs:element minOccurs="0" name="Condition">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="DirectionCondition">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="Direction" />
                          <xs:element minOccurs="0" name="Invert" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="InputMoveCondition">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="Invert" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="FindTargetAction">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="Time" />
              <xs:element minOccurs="0" name="Duration" />
              <xs:element minOccurs="0" name="Condition">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="DirectionCondition">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="Direction" />
                          <xs:element minOccurs="0" name="Invert" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="InputMoveCondition">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="Invert" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="MoveAction">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="Time" />
              <xs:element minOccurs="0" name="Duration" />
              <xs:element minOccurs="0" name="Condition">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="DirectionCondition">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="Direction" />
                          <xs:element minOccurs="0" name="Invert" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="InputMoveCondition">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="Invert" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="TranslationEvents">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="TranslationEvent">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="Time" />
              <xs:element minOccurs="0" name="ToState" />
              <xs:element minOccurs="0" name="Condition">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="DirectionCondition">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="Direction" />
                          <xs:element minOccurs="0" name="Invert" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="InputMoveCondition">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="Invert" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pZeroWind/Project_Fantasy/Assets/Resources/StateMachine/Player/PlayerMoveLState.xml
<?xml version="1.0" encoding="utf-8"?>
<State xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.com/stateMachine ../stateMachineSchema.xsd" xmlns="http://example.com/stateMachine">
	<ActionEvents>
		<!--播放向左移动动画-->
		<AnimationPlayAction>
			<Name>Move_L</Name>
		</AnimationPlayAction>
		<EffectPlayAction>
			<Name>EffectFugitiveDust</Name>
			<Time>0</Time>
		</EffectPlayAction>
		<EffectPlayAction>
			<Name>EffectFugitiveDust</Name>
			<Time>0.675</Time>
		</EffectPlayAction>
		<MoveAction>
			<Duration>1.35</Duration>
		</MoveAction>
	</ActionEvents>
	<TranslationEvents>
		<!--切换到向左待机状态-->
		<TranslationEvent>
			<ToState>PlayerIdleLState</ToState>
			<Condition>
				<InputMoveCondition>
					<Invert>true</Invert>
				</InputMoveCondition>
			</Condition>
		</TranslationEvent>
		<TranslationEvent>
			<ToState>PlayerMoveRState</ToState>
			<Condition>
				<DirectionCondition>
					<Direction>1</Direction>
				</DirectionCondition>
				<InputMoveCondition>
				</InputMoveCondition>
			</Condition>
		</TranslationEvent>
		<TranslationEvent>
			<Time>1.35</Time>
			<ToState>PlayerMoveLState</ToState>
			<Condition>
				<InputMoveCondition>
				</InputMoveCondition>
			</Condition>
		</TranslationEvent>
	</TranslationEvents>
</State>

=== pZeroWind/Project_Fantasy/Assets/Resources/StateMachine/Player/PlayerIdleLState.xml
<?xml version="1.0" encoding="utf-8"?>
<State xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.com/stateMachine ../stateMachineSchema.xsd" xmlns="http://example.com/stateMachine">
	<ActionEvents>
		<!--播放向左待机动画-->
		<AnimationPlayAction>
			<Name>Idle_L</Name>
		</AnimationPlayAction>
	</ActionEvents>
	<TranslationEvents>
		<!--切换到向左待机状态-->
		<TranslationEvent>
			<Time>0.84</Time>
			<ToState>PlayerIdleLState</ToState>
			<Condition>
				<InputMoveCondition>
					<Invert>true</Invert>
				</InputMoveCondition>
			</Condition>
		</TranslationEvent>
		<TranslationEvent>
			<ToState>PlayerMoveRState</ToState>
			<Condition>
				<InputMoveCondition>
				</InputMoveCondition>
			</Condition>
		</TranslationEvent>
	</TranslationEvents>
</State>
